platform :ios, '9.0'

target 'TheFirstApp' do
pod 'AFNetworking',  '~> 4.0.1'
pod 'SDWebImage',    '~> 5.10.0'
pod 'MJRefresh',     '~> 3.5.0'
pod 'MBProgressHUD', '~> 1.2.0'
pod 'Masonry',       '~> 1.1.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
